### ISSUE TITLE
ensemble consensus score reporting

### ISSUE THREAD

**Issue by davidballi** [andrewrech/antigen.garnish#1]
Hi Andrew,

Very cool project.  Some thoughts I had looking through your code.

1) Do we know if the distribution of affinity scores between netmhc* tools and mhcflurry are similar enough that taking the mean of scores is appropriate?  I have seen a general trend of mhcflurry reporting lower absolute affinity for very weak binder peptide compared to other tools (e.g. ic50 of 24000 vs 32000 netmhcpan).  If the distributions are different, perhaps taking the mean of percentage rank for a given peptide cohort may be better?

2) reporting 95% CI intervals for ensemble score.  For example, predicted affinity of SIINFEKL to HLA-A0201 is quite diverse between the tools:

- mchflurry 0.2.0:   10672.3
- netmhcpan3.0:    18233.3
- netmhc3.4:          12576.0

I know mhcflurry v1.0 is reporting upper and lower estimates for the ic50 values.

**Comment by andrewrech** [comment]
Hey @davidballi,

Thanks for your comments.

> distribution of affinity scores between netmhc* tools and mhcflurry ... perhaps taking the mean of percentage rank

I think the likely soon forthcoming performance comparison will probably be required to know. Since the available alleles for NetMHC and mhcflurry at the same, at least this should not be introducing bias and should be ~= equivalent to percentile rank.

> netMHC* vs. netMHC*pan

If the MHC allele is available for a non-pan tool then we're using only the non-pan tool, since we expect this to be significantly more accurate.

**Comment by andrewrech** [comment]
Will add mean for `mhcnuggets`

**Comment by andrewrech** [comment]
CI added #18
