### ISSUE TITLE
garnish_fitness is not returning `R` or `A` 

### ISSUE THREAD

**Issue by davidballi** [andrewrech/antigen.garnish#83]
Hey guys,

I noticed a few weird things tonight.  after calling `dt %>% garnish_fitness`, the output does not contain `A` or `R` as the [R manual](http://ihmvgkpeoiakxlajyewnrgxwtrtyevdmfzgdbjkmquaozqhbfgihmvgkpeoiaka.s3-website-us-east-1.amazonaws.com/antigen.garnish.pdf) says for that function.  Calling `dt$R` does return a string of letters:

```r
dt$R %>% head
[1] "C" "C" "C" "C" NA  "C"
```
which is the same output as calling the 'REF' nucleic acid:
```r
dt[1:6, REF]
[1] "C" "C" "C" "C" NA  "C"
```

any ideas or is the R manual not current?

**Comment by leeprichman** [comment]
R manual looks to be old. Decided to hide these and only return NeoantigenRecognitionPotential from Lukza model since I translated and implemented our version in R with last big merge.

**Comment by leeprichman** [comment]
garnish_fitness is also run internally within garnish_predictions, its not intended as a post-hoc step (though it was originally designed that way and basically runs right at the end of the workflow). Perhaps we need to change docs to make it clear that its an internal step?  Or force it to error if you try to run it on a table that already contains those values?

**Comment by davidballi** [comment]
Makes sense.  It is a minor issue, but python functions designed for internal use only start with an underscore (e.g. _GarnishFitness(dt=dt, a=1,k=4.12)), does R have a code style recommendation similar?  

From an end-user perspective, I would like to have Luksza's R returned in the final output dt.

**Comment by leeprichman** [comment]
No convention that I know of other than placing ‘.’before primitive functions, we could implement something though if it’s really confusing. Re R value, my emails with users made me feel like people gravitate toward the R value because they recognize it and not our implementation (iedb_score) which I would prefer they do. I did retain the Luksza et al output in the working directory and it can be easily obtained from that.  Maybe something in the vignette showing how to integrate that with the final output? I’d much rather not have it in the final data table we put out because I want people to use the antigen.garnish results and not just us as a wrapper for their scripts. There will also be a discrepancy between ours and theirs due to their tossing of certain variants that we keep, theirs only working on 9mers, and the slightly different substitution matrices. I’m afraid this would be a source of confusion. What do you both think?

**Comment by davidballi** [comment]
I'll defer to you as I did not realize your implementation of `R` was that much different.  Go ahead and close this out.

**Comment by andrewrech** [comment]
docs updated @leeprichman 

sorry they were old

**Comment by leeprichman** [comment]
Thank you both. Closing this out
